
file_type: csv
dataset_name: itineraries
file_name: itineraries
table_name: itinerary_data
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1
columns:
  - legId
  - searchDate
  - flightDate
  - startingAirport
  - destinationAirport
  - fareBasisCode
  - travelDuration
  - elapsedDays
  - isBasicEconomy
  - isRefundable
  - isNonStop
  - baseFare
  - totalFare
  - seatsRemaining
  - totalTravelDistance
  - segmentsDepartureTimeEpochSeconds
  - segmentsDepartureTimeRaw
  - segmentsArrivalTimeEpochSeconds
  - segmentsArrivalTimeRaw
  - segmentsArrivalAirportCode
  - segmentsDepartureAirportCode
  - segmentsAirlineName
  - segmentsAirlineCode
  - segmentsEquipmentDescription
  - segmentsDurationInSeconds
  - segmentsDistance
  - segmentsCabinCode
